STOCKS = [
      {"symbol": "VIC", "company_name": "Vingroup", "exchange": "HOSE"},
      {"symbol": "VCB", "company_name": "Vietcombank", "exchange": "HOSE"},
      {"symbol": "CTG", "company_name": "VietinBank", "exchange": "HOSE"},
      {"symbol": "HPG", "company_name": "Hoa Phat Group", "exchange": "HOSE"},
      {"symbol": "STB", "company_name": "Sacombank", "exchange": "HOSE"},
      {"symbol": "VNM", "company_name": "Vinamilk", "exchange": "HOSE"},
      {"symbol": "FPT", "company_name": "FPT Corporation", "exchange": "HOSE"},
      {"symbol": "MSN", "company_name": "Masan Group", "exchange": "HOSE"},
      {"symbol": "SSI", "company_name": "SSI Securities", "exchange": "HOSE"},
      {"symbol": "BVH", "company_name": "Bao Viet Holdings", "exchange": "HOSE"},
      {"symbol": "HCM", "company_name": "HSC Securities", "exchange": "HOSE"},
      {"symbol": "EIB", "company_name": "Eximbank", "exchange": "HOSE"},
      {"symbol": "GMD", "company_name": "Gemadept", "exchange": "HOSE"},
      {"symbol": "REE", "company_name": "REE Corporation", "exchange": "HOSE"},
      {"symbol": "KBC", "company_name": "Kinh Bac City Development", "exchange": "HOSE"},
      {"symbol": "VND", "company_name": "VNDirect Securities", "exchange": "HOSE"},
      {"symbol": "KDH", "company_name": "Khang Dien House", "exchange": "HOSE"},
      {"symbol": "SBT", "company_name": "TTC Sugar", "exchange": "HOSE"},
      {"symbol": "HAG", "company_name": "Hoang Anh Gia Lai", "exchange": "HOSE"},
      {"symbol": "PVD", "company_name": "PV Drilling", "exchange": "HOSE"},

      {"symbol": "ACB", "company_name": "Asia Commercial Bank", "exchange": "HOSE"},
      {"symbol": "BID", "company_name": "BIDV", "exchange": "HOSE"},
      {"symbol": "MBB", "company_name": "MB Bank", "exchange": "HOSE"},
      {"symbol": "TCB", "company_name": "Techcombank", "exchange": "HOSE"},
      {"symbol": "VPB", "company_name": "VPBank", "exchange": "HOSE"},
      {"symbol": "VIB", "company_name": "Vietnam International Bank", "exchange": "HOSE"},
      {"symbol": "OCB", "company_name": "Orient Commercial Bank", "exchange": "HOSE"},
      {"symbol": "SHB", "company_name": "Saigon-Hanoi Bank", "exchange": "HOSE"},
      {"symbol": "LPB", "company_name": "Loc Phat Vietnam Bank", "exchange": "HOSE"},
      {"symbol": "TPB", "company_name": "Tien Phong Bank", "exchange": "HOSE"},
      {"symbol": "MSB", "company_name": "Vietnam Maritime Bank", "exchange": "HOSE"},
      {"symbol": "HDB", "company_name": "HDBank", "exchange": "HOSE"},
      {"symbol": "VIX", "company_name": "VIX Securities", "exchange": "HOSE"},
      {"symbol": "VCI", "company_name": "Viet Capital Securities", "exchange": "HOSE"},
      {"symbol": "VDS", "company_name": "Viet Dragon Securities", "exchange": "HOSE"},
      {"symbol": "CTS", "company_name": "VietinBank Securities", "exchange": "HOSE"},
      {"symbol": "BSI", "company_name": "BIDV Securities", "exchange": "HOSE"},
      {"symbol": "ORS", "company_name": "Tien Phong Securities", "exchange": "HOSE"},
      {"symbol": "VCG", "company_name": "Vietnam Construction", "exchange": "HOSE"},
      {"symbol": "HHV", "company_name": "Deo Ca Traffic Infrastructure", "exchange": "HOSE"},
      {"symbol": "CII", "company_name": "Ho Chi Minh Infrastructure Investment", "exchange": "HOSE"},
      {"symbol": "DIG", "company_name": "Development Investment Construction", "exchange": "HOSE"},
      {"symbol": "DXG", "company_name": "Dat Xanh Group", "exchange": "HOSE"},
      {"symbol": "NLG", "company_name": "Nam Long Investment", "exchange": "HOSE"},
      {"symbol": "PDR", "company_name": "Phat Dat Real Estate", "exchange": "HOSE"},
      {"symbol": "NVL", "company_name": "Novaland Group", "exchange": "HOSE"},
      {"symbol": "CEO", "company_name": "C.E.O Group", "exchange": "HNX"},
      {"symbol": "IJC", "company_name": "Becamex Infrastructure Development", "exchange": "HOSE"},
      {"symbol": "KHG", "company_name": "Khai Hoan Land", "exchange": "HOSE"},
      {"symbol": "TCH", "company_name": "Hoang Huy Investment", "exchange": "HOSE"},
      {"symbol": "HDC", "company_name": "Ba Ria-Vung Tau House Development", "exchange": "HOSE"},
      {"symbol": "SZC", "company_name": "Sonadezi Chau Duc", "exchange": "HOSE"},
      {"symbol": "IDC", "company_name": "IDICO Corporation", "exchange": "HNX"},
      {"symbol": "BCM", "company_name": "Becamex IDC", "exchange": "HOSE"},
      {"symbol": "SIP", "company_name": "Saigon VRG Investment", "exchange": "HOSE"},
      {"symbol": "DGC", "company_name": "Duc Giang Chemicals", "exchange": "HOSE"},
      {"symbol": "DHG", "company_name": "DHG Pharmaceutical", "exchange": "HOSE"},
      {"symbol": "DPM", "company_name": "PetroVietnam Fertilizer", "exchange": "HOSE"},
      {"symbol": "DCM", "company_name": "PetroVietnam Ca Mau Fertilizer", "exchange": "HOSE"},
      {"symbol": "CSV", "company_name": "South Basic Chemicals", "exchange": "HOSE"},
      {"symbol": "NKG", "company_name": "Nam Kim Steel", "exchange": "HOSE"},
      {"symbol": "HSG", "company_name": "Hoa Sen Group", "exchange": "HOSE"},
      {"symbol": "TLH", "company_name": "Tien Len Steel", "exchange": "HOSE"},
      {"symbol": "VGS", "company_name": "Vietnam Germany Steel", "exchange": "HNX"},
      {"symbol": "VTP", "company_name": "Viettel Post", "exchange": "HOSE"},
      {"symbol": "MWG", "company_name": "Mobile World Investment", "exchange": "HOSE"},
      {"symbol": "PNJ", "company_name": "Phu Nhuan Jewelry", "exchange": "HOSE"},
      {"symbol": "DGW", "company_name": "Digiworld", "exchange": "HOSE"},
      {"symbol": "SAB", "company_name": "Sabeco", "exchange": "HOSE"},
      {"symbol": "BHN", "company_name": "Hanoi Beer Alcohol and Beverage", "exchange": "HOSE"},
      {"symbol": "VHC", "company_name": "Vinh Hoan", "exchange": "HOSE"},
      {"symbol": "ANV", "company_name": "Nam Viet", "exchange": "HOSE"},
      {"symbol": "IDI", "company_name": "International Development and Investment", "exchange": "HOSE"},
      {"symbol": "FMC", "company_name": "Sao Ta Foods", "exchange": "HOSE"},
      {"symbol": "ASM", "company_name": "Sao Mai Group", "exchange": "HOSE"},
      {"symbol": "HAX", "company_name": "Hang Xanh Motors Service", "exchange": "HOSE"},
      {"symbol": "PLX", "company_name": "Petrolimex", "exchange": "HOSE"},
      {"symbol": "GAS", "company_name": "PV Gas", "exchange": "HOSE"},
      {"symbol": "POW", "company_name": "PetroVietnam Power", "exchange": "HOSE"},
      {"symbol": "PPC", "company_name": "Pha Lai Thermal Power", "exchange": "HOSE"},
      {"symbol": "NT2", "company_name": "PetroVietnam Power Nhon Trach 2", "exchange": "HOSE"},
      {"symbol": "PHR", "company_name": "Phuoc Hoa Rubber", "exchange": "HOSE"},
      {"symbol": "DPR", "company_name": "Dong Phu Rubber", "exchange": "HOSE"},
      {"symbol": "VRE", "company_name": "Vincom Retail", "exchange": "HOSE"},
      {"symbol": "VHM", "company_name": "Vinhomes", "exchange": "HOSE"},
      {"symbol": "VJC", "company_name": "Vietjet Air", "exchange": "HOSE"},
      {"symbol": "HVN", "company_name": "Vietnam Airlines", "exchange": "HOSE"},
      {"symbol": "CTR", "company_name": "Viettel Construction", "exchange": "HOSE"},
      {"symbol": "BWE", "company_name": "Binh Duong Water", "exchange": "HOSE"},
      {"symbol": "QNS", "company_name": "Quang Ngai Sugar", "exchange": "UPCOM"},

      {"symbol": "VNINDEX", "company_name": "VN-Index", "exchange": "HOSE"},
      {"symbol": "VN30", "company_name": "VN30-Index", "exchange": "HOSE"},
      {"symbol": "E1VFVN30", "company_name": "DCVFMVN30 ETF", "exchange": "HOSE"},
      {"symbol": "FUEVFVND", "company_name": "DCVFMVN Diamond ETF", "exchange": "HOSE"},
      {"symbol": "FUESSVFL", "company_name": "SSIAM VNFIN Lead ETF", "exchange": "HOSE"},
      {"symbol": "FUEVN100", "company_name": "VinaCapital VN100 ETF", "exchange": "HOSE"},
      {"symbol": "FUEMAV30", "company_name": "Mirae Asset VN30 ETF", "exchange": "HOSE"},
      {"symbol": "FUEIP100", "company_name": "IPAAM VN100 ETF", "exchange": "HOSE"},
      {"symbol": "FUEDCMID", "company_name": "DCVFM VNMidcap ETF", "exchange": "HOSE"},
      {"symbol": "GB05F2506", "company_name": "Vietnam Government Bond", "exchange": "HNX"},
]

CONFIG = {
      "mode": "limit",
      "interval": "1D",
      "limit": 1250,
      "start_date": "2021-07-26",
      "end_date": "2026-07-26",
  }
 